 SELECT A.STRM, A.CLASS_NBR, A.CRSE_ID, A.CRSE_OFFER_NBR, A.CLASS_SECTION, A.SESSION_CODE,
  B.CLASS_MTG_NBR, A.SUBJECT, A.CATALOG_NBR, A.CAMPUS, A.LOCATION,
  A.DESCR AS TITLE, B.START_DT,
  B.MEETING_TIME_START, B.END_DT, B.MEETING_TIME_END, B.MON, B.TUES, B.WED, B.THURS,
  B.FRI, B.SAT, B.SUN, A.SCHEDULE_PRINT, B.FACILITY_ID, INSTRUCTOR.NAME_FORMAL,
  INSTRUCTOR.NAME, INSTRUCTOR.FIRST_NAME, INSTRUCTOR.LAST_NAME, CI.INSTR_ROLE, A.ENRL_TOT,
  A.ENRL_CAP, A.WAIT_TOT, A.WAIT_CAP, 
  A.ACAD_CAREER,
  A.SSR_COMPONENT,
  A.CONSENT , A.CRS_TOPIC_ID,
  A.ENRL_STAT, A.CLASS_STAT, A.INSTRUCTION_MODE ,
  A.ACAD_GROUP, A.ACAD_ORG, CI.SCHED_PRINT_INSTR
  FROM PS_CLASS_TBL A , PS_CLASS_MTG_PAT B , PS_NAMES INSTRUCTOR , PS_CLASS_INSTR CI
 WHERE 
   A.CRSE_ID = B.CRSE_ID
   AND A.CRSE_OFFER_NBR = B.CRSE_OFFER_NBR
   AND A.STRM = B.STRM
   AND A.SESSION_CODE = B.SESSION_CODE
   AND A.CLASS_SECTION = B.CLASS_SECTION
   AND CI.CRSE_ID = B.CRSE_ID
   AND CI.CRSE_OFFER_NBR = B.CRSE_OFFER_NBR
   AND CI.STRM = B.STRM
   AND CI.SESSION_CODE = B.SESSION_CODE
   AND CI.CLASS_SECTION = B.CLASS_SECTION
   AND CI.CLASS_MTG_NBR = B.CLASS_MTG_NBR
   AND CI.EMPLID = INSTRUCTOR.EMPLID
   AND 'PRI' = INSTRUCTOR.NAME_TYPE 
   AND (INSTRUCTOR.EFFDT = (
 SELECT MAX(INSTRUCTOR_ED.EFFDT)
  FROM PS_NAMES INSTRUCTOR_ED
 WHERE INSTRUCTOR_ED.EMPLID = INSTRUCTOR.EMPLID
   AND INSTRUCTOR_ED.NAME_TYPE = INSTRUCTOR.NAME_TYPE
   AND INSTRUCTOR_ED.EFFDT <= ? )
    OR INSTRUCTOR.EFFDT IS NULL)
   AND 'A' = INSTRUCTOR.EFF_STATUS 
   AND A.STRM >= '2077'
