
  CREATE TABLE "PS_CLASS_MTG_PAT"
   (
	"CRSE_ID" VARCHAR(6) NOT NULL,
	"CRSE_OFFER_NBR" INTEGER NOT NULL,
	"STRM" VARCHAR(4) NOT NULL,
	"SESSION_CODE" VARCHAR(3) NOT NULL,
	"CLASS_SECTION" VARCHAR(4) NOT NULL,
	"CLASS_MTG_NBR" INTEGER NOT NULL,
	"FACILITY_ID" VARCHAR(10) NOT NULL,
	"MEETING_TIME_START" DATE,
	"MEETING_TIME_END" DATE,
	"MON" VARCHAR(1) NOT NULL,
	"TUES" VARCHAR(1) NOT NULL,
	"WED" VARCHAR(1) NOT NULL,
	"THURS" VARCHAR(1) NOT NULL,
	"FRI" VARCHAR(1) NOT NULL,
	"SAT" VARCHAR(1) NOT NULL,
	"SUN" VARCHAR(1) NOT NULL,
	"START_DT" DATE NOT NULL,
	"END_DT" DATE NOT NULL,
	"CRS_TOPIC_ID" INTEGER NOT NULL,
	"DESCR" VARCHAR(30) NOT NULL,
	"STND_MTG_PAT" VARCHAR(4) NOT NULL,
	"PRINT_TOPIC_ON_XCR" VARCHAR(1) NOT NULL
   );


  CREATE UNIQUE INDEX "PS_CLASS_MTG_PAT" ON "PS_CLASS_MTG_PAT" ("CRSE_ID", "CRSE_OFFER_NBR", "STRM", "SESSION_CODE", "CLASS_SECTION", "CLASS_MTG_NBR");

