CREATE TABLE "PS_CLASS_INSTR"
   (
	"CRSE_ID" VARCHAR(6) NOT NULL,
	"CRSE_OFFER_NBR" INTEGER NOT NULL,
	"STRM" VARCHAR(4) NOT NULL,
	"SESSION_CODE" VARCHAR(3) NOT NULL,
	"CLASS_SECTION" VARCHAR(4) NOT NULL,
	"CLASS_MTG_NBR" INTEGER NOT NULL,
	"INSTR_ASSIGN_SEQ" INTEGER NOT NULL,
	"EMPLID" VARCHAR(11) NOT NULL,
	"INSTR_ROLE" VARCHAR(4) NOT NULL,
	"GRADE_RSTR_ACCESS" VARCHAR(1) NOT NULL,
	"CONTACT_MINUTES" INTEGER NOT NULL,
	"SCHED_PRINT_INSTR" VARCHAR(1) NOT NULL,
	"INSTR_LOAD_FACTOR" DECIMAL(10,4) NOT NULL,
	"EMPL_RCD" INTEGER NOT NULL,
	"ASSIGN_TYPE" VARCHAR(3) NOT NULL,
	"WEEK_WORKLOAD_HRS" DECIMAL(5,2) NOT NULL,
	"ASSIGNMENT_PCT" DECIMAL(5,2) NOT NULL,
	"AUTO_CALC_WRKLD" VARCHAR(1) NOT NULL
   );


CREATE INDEX "PS0CLASS_INSTR" ON "PS_CLASS_INSTR" ("EMPLID", "CRSE_ID", "CRSE_OFFER_NBR", "STRM" DESC, "SESSION_CODE", "CLASS_SECTION", "CLASS_MTG_NBR", "INSTR_ASSIGN_SEQ");

CREATE UNIQUE INDEX "PS_CLASS_INSTR" ON "PS_CLASS_INSTR" ("CRSE_ID", "CRSE_OFFER_NBR", "STRM" DESC, "SESSION_CODE", "CLASS_SECTION", "CLASS_MTG_NBR", "INSTR_ASSIGN_SEQ");

